Blog-Page/Controllers/LoginController.cs
using BlogNET.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Linq;

namespace BlogNET.Controllers
{
    public class LoginController : Controller
    {
        private readonly BlogDbContext _context;
        private IConfiguration _configuration;

        public LoginController(BlogDbContext context, IConfiguration configuration)
        {
            _configuration = configuration;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }


        //[AllowAnonymous]
        // authorization  - yetki
        // authentication - kimlik kanıtlama
        //[Authorize(Roles = "SuperAdmin")]
        //public IActionResult Super()
        //{
        //    string token = HttpContext.Session.GetString("ali");
        //    return View();
        //}

        [HttpPost]
        public async Task<IActionResult> Index(Author model) // home login e gidiyor. o yüzden düzeltmeler yappp.
        {
            using (SHA256 sha256 = SHA256.Create())
            {

                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                byte[] passwordBytes = Encoding.UTF8.GetBytes(model.Password); // Parolayı byte dizisine dönüştür
                byte[] hashBytes = sha256.ComputeHash(passwordBytes); // Byte dizisini SHA-256 ile hashle

                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < hashBytes.Length; i++)
                {
                    sb.Append(hashBytes[i].ToString("x2")); // Her byte'ı hexadecimal formata dönüştürerek string olarak birleştir
                }

                string hashedPassword = sb.ToString();

                var emailParam = new SqlParameter("@Email", model.Email.ToLower());
                var passwordParam = new SqlParameter("@Password", hashedPassword);

                var query = "SELECT TOP 1 * FROM Author WHERE Email = @Email AND Password = @Password";
                //TOP 1 İstenen sonucun sadece ilk kaydı olduğu biliniyorsa, bu ifade kullanılarak sorgunun performansı artırılabilir.

                var author = await _context.Author.FromSqlRaw(query, emailParam, passwordParam).FirstOrDefaultAsync();

                if (author == null)
                {
                    return RedirectToAction("Index");
                }
                else if (author.Role == "SuperAdmin")
                {
                    HttpContext.Session.SetString("superAdmin", "superAdmin");
                    return RedirectToAction("Index", "Blog");
                }
                //var token = Generate(author);
                //HttpContext.Session.SetString("token", token);
                HttpContext.Session.SetInt32("Id", author.Id);
                return RedirectToAction("Index", "AdminBlog");
            }
        }

        //private string Generate(Author user)
        //{
        //    var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["Jwt:Key"]));
        //    var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256);

        //    var claims = new[]
        //    {
        //        new Claim(ClaimTypes.NameIdentifier, user.Name),
        //        new Claim(ClaimTypes.Email, user.Email),
        //        new Claim(ClaimTypes.Surname, user.Surname),
        //        new Claim(ClaimTypes.Role, user.Role)
        //    };


        //    var token = new JwtSecurityToken(_configuration["Jwt:Issuer"],
        //      _configuration["Jwt:Audience"],
        //      claims,
        //      expires: DateTime.Now.AddMinutes(15),
        //      signingCredentials: credentials);

        //    return new JwtSecurityTokenHandler().WriteToken(token);
        //}



        //private Author Authenticate(Author userLogin)
        //{
        //    var currentUser = _context.Author.FirstOrDefault(o => o.Email.ToLower() == userLogin.Email.ToLower() && o.Password == userLogin.Password);

        //    if (currentUser != null)
        //    {
        //        return currentUser;
        //    }

        //    return null;
        //}



    }
}

Blog-Page/Controllers/RegisterController.cs
using BlogNET.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace BlogNET.Controllers
{
    public class RegisterController : Controller
    {
        private readonly BlogDbContext _context;


        public RegisterController(BlogDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Index(Author author)
        {
            
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] passwordBytes = Encoding.UTF8.GetBytes(author.Password); // Parolayı byte dizisine dönüştür
                byte[] hashBytes = sha256.ComputeHash(passwordBytes); // Byte dizisini SHA-256 ile hashle

                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < hashBytes.Length; i++)
                {
                    sb.Append(hashBytes[i].ToString("x2")); // Her byte'ı hexadecimal formata dönüştürerek string olarak birleştir
                }

                string hashedPassword = sb.ToString();

                var sql = "INSERT INTO Author (Name, Surname, Email, Password, Role) VALUES (@Name, @Surname, @Email, @Password, @Role)";

                var parameters = new List<SqlParameter>();
                parameters.Add(new SqlParameter("@Name", author.Name));
                parameters.Add(new SqlParameter("@Surname", author.Surname));
                parameters.Add(new SqlParameter("@Email", author.Email));
                parameters.Add(new SqlParameter("@Password", hashedPassword)); // Hashlenmiş parolayı kullan
                parameters.Add(new SqlParameter("@Role", "Admin")); // Hashlenmiş parolayı kullan

                await _context.Database.ExecuteSqlRawAsync(sql, parameters);
                ViewBag.kayitbasarili = true;

                
                return View();
            }

        }
    }
}

Blog-Page/Views/Login/Index.cshtml
@model BlogNET.Models.Author
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<header>
    <section class="main-content-w3layouts-agileits">
        <div class="container">
            <h3 class="tittle">Giriş Yap</h3>
            <div class="row inner-sec">
                <div class="login p-5 bg-light mx-auto mw-100">
                    <form asp-action="Index" asp-controller="Login" method="post">
                        <div class="form-group">
                            <label for="exampleInputEmail1 mb-2">Email adresi</label>
                            <input type="email" asp-for="Email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email">
                            <small id="emailHelp" class="form-text text-muted">E-postanızı asla başkasıyla paylaşmayacağız.</small>
                            <span asp-validation-for="Email"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1 mb-2">Şifre</label>
                            <input type="password" asp-for="Password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                            <span asp-validation-for="Password" class="text-danger"></span>

                        </div>
                        @*<div class="form-check mb-2">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Check me out</label>
                        </div>*@
                        <button type="submit" class="btn btn-primary submit mb-4">Giriş Yap</button>
                        <p><a asp-action="Index" asp-controller="Register">Bir hesabınız yok mu ?</a></p>
                        <div class="userinfo">
                            <h5><u>Hazır Girişler</u></h5>
                            <h5>Superadmin</h5>
                            <h5>Eposta: superadmin@gmail.com</h5>
                            <h5>Sifre: superadmin</h5>
                            <h5>---------</h5>
                            <h5>Admin</h5>
                            <h5>Eposta: admin@gmail.com</h5>
                            <h5>Sifre: admin1</h5>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</header>

Blog-Page/Views/Login/Super.cshtml
@{
    ViewData["Title"] = "Super";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h1>Super</h1>