Blog-Page/Controllers/AuthorController.cs
using BlogNET.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace BlogNET.Controllers
{
    public class AuthorController : Controller
    {

        private readonly ILogger<AuthorController> _logger;
        private readonly BlogDbContext _context;

        public AuthorController(ILogger<AuthorController> logger, BlogDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        //[Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> AddAuthor(Author author)
        {

            if (HttpContext.Session.GetString("superAdmin") != "superAdmin")
            {
                //var list = _context.Blog.ToList();    
                return RedirectToAction("Forbidden", "Error");
            }

            // SHA-256 hash hesaplama
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] passwordBytes = Encoding.UTF8.GetBytes(author.Password); // Parolayı byte dizisine dönüştür
                byte[] hashBytes = sha256.ComputeHash(passwordBytes); // Byte dizisini SHA-256 ile hashle

                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < hashBytes.Length; i++)
                {
                    sb.Append(hashBytes[i].ToString("x2")); // Her byte'ı hexadecimal formata dönüştürerek string olarak birleştir
                }

                string hashedPassword = sb.ToString();

                var sql = "INSERT INTO Author (Name, Surname, Email, Password, Role) VALUES (@Name, @Surname, @Email, @Password, @Role)";

                var parameters = new List<SqlParameter>();
                parameters.Add(new SqlParameter("@Name", author.Name));
                parameters.Add(new SqlParameter("@Surname", author.Surname));
                parameters.Add(new SqlParameter("@Email", author.Email));
                parameters.Add(new SqlParameter("@Password", hashedPassword)); // Hashlenmiş parolayı kullan
                parameters.Add(new SqlParameter("@Role", author.Role));


                await _context.Database.ExecuteSqlRawAsync(sql, parameters);

                return Json(true);
            }

        }

        //[Authorize(Roles = "SuperAdmin")]
        [HttpPost]
        public async Task<IActionResult> UpdateAuthor(Author author) // burada kaldık
        {
            if (HttpContext.Session.GetString("superAdmin") != "superAdmin")
            {
                //var list = _context.Blog.ToList();    
                return RedirectToAction("Forbidden", "Error");
            }

            //var sqll = "UPDATE Author SET Name = @Name, Surname = @Surname, Email = @Email, Role = @Role  WHERE Id = @Id";

            //var parameters = new List<SqlParameter>();
            //parameters.Add(new SqlParameter("@Name", author.Name));
            //parameters.Add(new SqlParameter("@Surname", author.Surname));
            //parameters.Add(new SqlParameter("@Email", author.Email));
            //parameters.Add(new SqlParameter("@Role", author.Role));
            //parameters.Add(new SqlParameter("@Id", author.Id));

            //await _context.Database.ExecuteSqlRawAsync(sqll, parameters);

            var existingAuthor = await _context.Author.FindAsync(author.Id);

            if (existingAuthor == null)
            {
                return NotFound(); // Varsayılan olarak 404 dönebilirsiniz.
            }

            existingAuthor.Name = author.Name;
            existingAuthor.Surname = author.Surname;
            existingAuthor.Email = author.Email;
            existingAuthor.Role = author.Role;

            await _context.SaveChangesAsync();


            return Json(true);
        }


        //[Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> AuthorDetails(int Id) // ?
        {
            if (HttpContext.Session.GetString("superAdmin") != "superAdmin")
            {
                //var list = _context.Blog.ToList();    
                return RedirectToAction("Forbidden", "Error");
            }

            var author = await _context.Author.FindAsync(Id);
            return Json(author);
        }



        //[Authorize(Roles = "SuperAdmin")]
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("superAdmin") != "superAdmin")
            {
                //var list = _context.Blog.ToList();    
                return RedirectToAction("Forbidden", "Error");
            }

            List<Author> list = _context.Author.OrderBy(a => a.Id).ToList();
            return View(list);
        }







        //[Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> DeleteAuthor(int Id)
        {
            if (HttpContext.Session.GetString("superAdmin") != "superAdmin")
            {
                //var list = _context.Blog.ToList();    
                return RedirectToAction("Forbidden", "Error");
            }

            var authorToDelete = _context.Author.FirstOrDefault(c => c.Id == Id);

            if (authorToDelete != null)
            {
                _context.Author.Remove(authorToDelete);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }


    }
}

Blog-Page/Controllers/BlogController.cs
using BlogNET.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BlogNET.Controllers
{
    public class BlogController : Controller
    {
        private readonly BlogDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BlogController(BlogDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        

        public IActionResult Index(int cno, int authorno)
        {
            List<Blog> blogs;

            //ViewBag.BlogNotFound = false;
                

            var categoryName = _context.Category
            .Where(a => a.Id == cno)
            .Select(a => a.Name)
            .FirstOrDefault() ?? "Kategori Bulunamadı";
            
            var authorName = _context.Author
            .Where(a => a.Id == authorno)
            .Select(a => a.Name)
            .FirstOrDefault() ?? "Yazar Bulunamadı";



            if (cno != 0) // return View at, hangi view ise hata yer alsın.
            {
                ViewBag.PageTitle = categoryName;

                blogs = _context.Blog
                .Where(b => b.CategoryId == cno && b.IsPublish && !(b.IsBlocked)) // CategoryId sütunu ile cno'yu karşılaştır
                .OrderByDescending(b => b.CreateTime)
                .ToList();
            }

            else if (authorno != 0) // return View at, hangi view ise hata yer alsın.
            {   
                ViewBag.PageTitle = "Yazar: " + authorName;

                blogs = _context.Blog
                .Where(b => b.AuthorId == authorno && b.IsPublish && !(b.IsBlocked)) // CategoryId sütunu ile cno'yu karşılaştır
                .OrderByDescending(b => b.CreateTime)
                .ToList();
            }
            else
            {
                ViewBag.PageTitle = "Tüm Bloglar";

                blogs = _context.Blog
                    .Where(b => b.IsPublish == true && !(b.IsBlocked))
                    .OrderByDescending(b => b.CreateTime)
                    .ToList();
            }

            //if (blogs.Count() == 0 && categoryName != null) // kategoride bir blog yok
            if (blogs.Count == 0 && categoryName != "Kategori Bulunamadı")
            {
                ViewBag.notFoundAlert = "Blog Paylaşımı Yok";
            }
            else
            {
                ViewBag.notFoundAlert = "";
            }

            return View(blogs);
        }

        public IActionResult Details(int Id) // parametre olarak alma.
        {
            //var categoryNames = _context.Category.Select(c => c.Name).ToList();
            //ViewBag.categoryNames = categoryNames.GetRange(0, 3);

            var blog = _context.Blog.Find(Id);
            //Burada
            return View(blog);
            //return View();
            // üstteki sorgu ile List gönderiyoruz ama 1 tek blog göndereceğiz. bunun detayına bak.
        }


        //[Authorize(Roles = "SuperAdmin, Admin")]
        public IActionResult Publish(int Id) // yayinlama islemini tersine cevirir.
        {
            var id = HttpContext.Session.GetInt32("Id");
            if (HttpContext.Session.GetString("superAdmin") != "superAdmin" && id == null)
            {
                //var list = _context.Blog.ToList();    
                return RedirectToAction("Forbidden", "Error");
            }

            var blog = _context.Blog.Find(Id);

            blog.IsPublish = !(blog.IsPublish);
            _context.Update(blog);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        




        //[Authorize(Roles = "Admin")]
        public IActionResult Add() // Categories'e gonderiliyor.
        {
            var id = HttpContext.Session.GetInt32("Id");
            if (id == null)
            {
                //var list = _context.Blog.ToList();    
                return RedirectToAction("Forbidden", "Error");
            }

            List<SelectListItem> values = _context.Category.Select(w =>
                new SelectListItem
                {
                    Text = w.Name,
                    Value = w.Id.ToString()
                }
            ).ToList();
            ViewBag.Values = values;
            return View();
        }



        //[Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Add(Blog model) // Category.Id elimizde. 
        {
            var id = HttpContext.Session.GetInt32("Id");
            if (id == null)
            {
                //var list = _context.Blog.ToList();    
                return RedirectToAction("Forbidden", "Error");
            }

            //if (!ModelState.IsValid) burada return View(model) yapamadığımız için validation kısmında sorun yaşanıyor.
            //{
            //    return View(model);
            //}

            if (model.CoverFoto != null)
            {
                // category name ekleme
                model.IsPublish = false;
                model.IsBlocked = false;

                string ContentRootPath = _webHostEnvironment.ContentRootPath;

                string folder = "images/";
                folder += Guid.NewGuid().ToString() + model.CoverFoto.FileName;

                string serverFolder = ContentRootPath + "/wwwroot/" + folder;

                model.ImagePath = folder;


                await model.CoverFoto.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                model.AuthorId = (int)HttpContext.Session.GetInt32("Id");

                await _context.AddAsync(model);
                await _context.SaveChangesAsync();
                return Json(true);
            }


            return Json(false);
        }



        //[Authorize(Roles = "SuperAdmin, Admin")]
        public async Task<IActionResult> DeleteBlog(int id2)
        {
            var id = HttpContext.Session.GetInt32("Id");
            if (HttpContext.Session.GetString("superAdmin") != "superAdmin" && id == null)
            {
                return RedirectToAction("Forbidden", "Error");
            }
            // YAPILACAK: Herkesin kendi blogunu silmesi icin kontol et.
            // YAPILACAK: Guncellemede de yap



            var blogToDelete = await _context.Blog.FindAsync(id2);

            if (blogToDelete == null)
            {
                // Blog bulunamazsa HTTP 404 (Not Found) döndürün
                return NotFound();
            }

            // Blog bulunduğunda doğrudan silme işlemini gerçekleştiririz.
            _context.Blog.Remove(blogToDelete);


            // Değişiklikleri veritabanına kaydedin
            await _context.SaveChangesAsync();
            // Silme işlemi başarılı olduğunda HTTP 200 (OK) döndürün
            return Ok(new { success = true });
        }

        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Comment()
        {
            var id = HttpContext.Session.GetInt32("Id");
            if (id == null)
            {
                return RedirectToAction("Forbidden", "Error");
            }




            await _context.SaveChangesAsync();
            return Json(true);
        }

        public IActionResult Content()
        {
            return View();
        }


    }



}

Blog-Page/Views/Shared/FooterPartial.cshtml
<footer style="background-color: #101010">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 footer-grid-agileits-w3ls text-left">
                <div>
                    <h3 style="color:white;">Bu Websitesi'ni Kim Tasarladı???</h3>
                    <p style="color:white;">Emirhan Sesigür, Bursa Teknik Üniversitesi Bilgisayar Mühendisliği 3. sınıf öğrencisi.</p>

                    <ul>
                        <li class="mx-3">
                            <a class="github" href="https://github.com/emirhansesigur/">
                                <i class="fab fa-github"></i>
                                <span>GitHub</span>
                            </a>
                        </li>
                        <li class="mx-3">
                            <a class="linkedin" href="https://www.linkedin.com/in/emirhansesigur/">
                                <i class="fab fa-linkedin"></i>
                                <span>LinkedIn</span>
                            </a>
                        </li>
                    </ul>
                </div>
                @*<div class="read">
                    <a href="single.html" class="btn btn-primary read-m">Read More</a>
                </div>*@
            </div>
            <div class="col-lg-4 footer-grid-agileits-w3ls text-left">

                <div class="tech-btm">
                    <h3>Son Gönderiler</h3>
                    @*<div class="blog-grids row mb-3">
                    <div class="col-md-5 blog-grid-left">
                    <a href="single.html">
                    <img src="~/CoreBlogTema/images/4.jpg" class="card-img-top img-fluid" alt="">
                    </a>
                    </div>
                    <div class="col-md-7 blog-grid-right">

                    <h5>
                    <a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
                    </h5>
                    <div class="sub-meta">
                    <span>
                    <i class="far fa-clock"></i> 20 Jan, 2018
                    </span>
                    </div>
                    </div>
                    </div>
                    <div class="blog-grids row mb-3">
                    <div class="col-md-5 blog-grid-left">
                    <a href="single.html">
                    <img src="~/CoreBlogTema/images/6.jpg" class="card-img-top img-fluid" alt="">
                    </a>
                    </div>
                    <div class="col-md-7 blog-grid-right">

                    <h5>
                    <a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
                    </h5>
                    <div class="sub-meta">
                    <span>
                    <i class="far fa-clock"></i> 20 Jan, 2018
                    </span>
                    </div>
                    </div>

                    </div>*@
                </div>
            </div>
            <!-- subscribe -->
            <div class="col-lg-4 subscribe-main footer-grid-agileits-w3ls text-left">
                <h2>Haber bültenimize kaydolun</h2>
                @*<div class="subscribe-main text-left">
                <div class="subscribe-form">
                <form class="subscribe_form" autocomplete="off">
                <input class="form-control" type="email" id="Email" placeholder="Enter your email..." required="">
                <button type="button" id="SaveNewsLetter"class="btn btn-primary">Gönder</button>
                </form>
                <div class="clearfix"> </div>
            </div>
            <p>We respect your privacy.No spam ever!</p>
        </div>*@
        <!-- //subscribe -->
    </div>
    </div>
    <!-- footer -->
    <div class="footer-cpy text-center">
        <div class="footer-social">
            <div class="copyrighttop">
                <ul>
                    <li class="mx-3">
                        <a class="github" href="https://github.com/emirhansesigur/">
                            <i class="fab fa-github"></i>
                            <span>GitHub</span>
                        </a>
                    </li>
                    <li>
                        <a class="linkedin" href="https://www.linkedin.com/in/emirhansesigur/">
                            <i class="fab fa-linkedin"></i>
                            <span>LinkedIn</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="w3layouts-agile-copyrightbottom">
            <p>
                © 2018 Weblog. All Rights Reserved | Design by
                <a href="http://w3layouts.com/">W3layouts</a>
            </p>
        </div>
    </div>


    <!-- //footer -->
    </div>
</footer>


@*
@section Scripts{

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>

        function SaveNewsLetter() {
            var email = document.getElementById("Email").value;

            var emailReg = /^([\w-\.]+@@([\w-]+\.)+[\w-]{2,4})?$/;

            // email form kontrol et.

            if (email == "") {
                swal.fire({
                    icon: 'error',
                    title: 'Hata!',
                    text: 'Bir email giriniz.',
                    confirmButtonText: 'Tamam'
                });
            }
            else if (!emailReg.test(email)) {
                swal.fire({
                    icon: 'error',
                    title: 'Hata!',
                    text: 'Email hatası.',
                    confirmButtonText: 'Tamam'
                });
            }
            else {
                $.ajax({
                    type: "POST",
                    dataType: 'json',
                    url: "@Url.Action("Newsletter", "Home")",
                    data: {
                        Email: email
                    },
                    success: function (data) {
                        if (data) {
                            swal.fire({
                                icon: 'success',
                                title: 'Başarılı!',
                                text: 'Kayıt işlemi başarılı..',
                                confirmButtonText: 'Tamam'
                            }).then(function () {
                                location.reload();
                            });
                        }
                        else {
                            swal.fire({
                                icon: 'error',
                                title: 'Hata!',
                                text: 'Bir hata oluştu.',
                                confirmButtonText: 'Tamam'
                            });
                        }
                    }
                });
            }
        }


        //$('#SaveNewsLetter').click(function () {
        //    console.log("emirhan");

        //    var email = document.getElementById("Email").value;

        //    //var emailReg = /^([\w-\.]+@@([\w-]+\.)+[\w-]{2,4})?$/;

        //    // email form kontrol et.

        //    if (email == "") {
        //        swal.fire({
        //            icon: 'error',
        //            title: 'Hata!',
        //            text: 'Bir email giriniz.',
        //            confirmButtonText: 'Tamam'
        //        });
        //    }
        //    else if (!emailReg.test(email)) {
        //        swal.fire({
        //            icon: 'error',
        //            title: 'Hata!',
        //            text: 'Email hatası.',
        //            confirmButtonText: 'Tamam'
        //        });
        //    }
        //    else {
        //        $.ajax({
        //            type: "POST",
        //            dataType: 'json',
        //            url: "@Url.Action("Newsletter", "Home")",
        //            data: {
        //                Email: email
        //            },
        //            success: function (data) {
        //                if (data) {
        //                    swal.fire({
        //                        icon: 'success',
        //                        title: 'Başarılı!',
        //                        text: 'Kayıt işlemi başarılı..',
        //                        confirmButtonText: 'Tamam'
        //                    }).then(function () {
        //                        location.reload();
        //                    });
        //                }
        //                else {
        //                    swal.fire({
        //                        icon: 'error',
        //                        title: 'Hata!',
        //                        text: 'Bir hata oluştu.',
        //                        confirmButtonText: 'Tamam'
        //                    });
        //                }
        //            }
        //        });
        //    }




        //});


    </script>


}

*@

Blog-Page/Views/Shared/HeaderPartial.cshtml
@using Microsoft.AspNetCore.Http;
@inject BlogDbContext _context

@{
    int? id = Context.Session.GetInt32("Id");
    string superAdmin = Context.Session.GetString("superAdmin");
    // sorgu at
    //var author = _context.Author.FirstOrDefault(a => a.Id == @x.AuthorId);
    var categories = _context.Category.ToList();
}


<div class="header_top" id="home">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right mx-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">
                        AnaSayfa
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Yazarlar</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="kategoriDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Karegoriler
                    </a>
                    <div class="dropdown-menu" aria-labelledby="kategoriDropdown">
                        @foreach (var category in categories)
                        {
                            <a class="dropdown-item" asp-route-cno="@category.Id" asp-action="Index" asp-controller="Blog">@category.Name</a>
                        }
                    </div>
                </li>

                @if (id.HasValue)
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="AdminBlog">Blogların</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Add" asp-controller="Blog">Blog Ekle</a>
                    </li>
                }


                @*<li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="kategoriDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Kategoriler
                </a>
                <div class="dropdown-menu" aria-labelledby="kategoriDropdown">
                @{
                if (!string.IsNullOrEmpty(ViewBag.categories))
                {
                @foreach (var x in ViewBag.categories)
                {
                <a class="dropdown-item" href="#">@x.Name</a>
                }
                }
                }
                </div>
                </li>*@
                @if (superAdmin == "superAdmin")
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="kategoriDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Super Admin
                        </a>
                        <div class="dropdown-menu" aria-labelledby="kategoriDropdown">
                            <a class="dropdown-item" asp-action="Index" asp-controller="Author">Kullanıcılar</a>
                            <a class="dropdown-item" asp-action="Index" asp-controller="AdminBlog">Tüm Bloglar</a>
                            <a class="dropdown-item" asp-action="Index" asp-controller="Category">Kategoriler</a>
                        </div>
                    </li>
                }
            </ul>
            <form action="#" method="post" class="form-inline my-2 my-lg-0 header-search">
                <input class="form-control mr-sm-2" type="search" placeholder="Aranacak Kelime..." name="Search" required="">
                <button class="btn btn1 my-2 my-sm-0" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </form>



        </div>
    </nav>

</div>

Blog-Page/Views/Shared/PageTopPartial.cshtml
@using Microsoft.AspNetCore.Http;

@{
    int? id = Context.Session.GetInt32("Id");
    string superAdmin = Context.Session.GetString("superAdmin");
}

<div class="col-md-4 top-forms text-center mt-lg-3 mt-md-1 mt-0">

    @if (id.HasValue || (superAdmin == "superAdmin")) // biri varsa
    {
        <span>Hoşgeldin... @superAdmin @*__kullanici_adi*@ </span>
    }


    @if (id.HasValue == false && (superAdmin != "superAdmin")) // ikisi de yoksa
    {
        <span class="mx-lg-4 mx-md-2  mx-1">
            <a href="/login">
                <i class="fas fa-lock"></i> Giriş Yap
            </a>
        </span>
        <span>
            <a href="/register">
                <i class="far fa-user"></i> Kaydol
            </a>
        </span>
    }

    @if (id.HasValue || (superAdmin == "superAdmin"))
    {

        <a href="/Home/LogOut" class="btn btn-secondary">Çıkış Yap</a>

    }
</div>

Blog-Page/Views/Shared/_UserLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Weblog a Blogging Category Bootstrap responsive WebTemplate | Blog3 :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Weblog a Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <link href="~/CoreBlogTema/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="~/CoreBlogTema/css/single.css">
    <link href="~/CoreBlogTema/css/style.css" rel='stylesheet' type='text/css' />
    <link href="~/CoreBlogTema/css/fontawesome-all.css" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800"
          rel="stylesheet">

</head>

<body>

    <header>
        <div class="top-bar_sub_w3layouts container-fluid">
            <div class="row">
                <div class="col-md-4 logo text-left">
                    <a class="navbar-brand" href="/">
                        <i class="fab fa-linode"></i> Weblog
                    </a>
                </div>
                @await Html.PartialAsync("PageTopPartial")

            </div>
        </div>

        @await Html.PartialAsync("HeaderPartial")


    </header>
    <!--//header-->

    <!--/main-->
    <script src="~/CoreBlogTema/js/jquery-2.2.3.min.js"></script>
    <script src="~/CoreBlogTema/js/bootstrap.js"></script>

    
    @RenderBody();
    <!--//main-->
    <!--footer-->
    @await Html.PartialAsync("FooterPartial")

    @RenderSection("Scripts", required: false) @*Session i renden edebilmesi icin*@
    <!---->
    <!-- js -->
    <!-- //js -->
    <!--/ start-smoth-scrolling -->
    <script src="~/CoreBlogTema/js/move-top.js"></script>
    <script src="~/CoreBlogTema/js/easing.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, 900);
            });
        });
    </script>
    <!--// end-smoth-scrolling -->

    <script>
        $(document).ready(function () {
            /*
                                    var defaults = {
                                            containerID: 'toTop', // fading element id
                                        containerHoverID: 'toTopHover', // fading element hover id
                                        scrollSpeed: 1200,
                                        easingType: 'linear'
                                        };
                                    */

            $().UItoTop({
                easingType: 'easeOutQuart'
            });

        });
    </script>
    <a href="#home" class="scroll" id="toTop" style="display: block;">
        <span id="toTopHover" style="opacity: 1;"> </span>
    </a>

    <!-- //Custom-JavaScript-File-Links -->



</body>

</html>
    